name: Post welcome comment
# https://github.com/ArtiomLK/skills-hello-github-actions
# https://learn.microsoft.com/en-us/training/modules/github-actions-automate-tasks/3-exercise-create-container-action

on:
  pull_request:
    types: [ opened ]
permissions:
  pull-requests: write

jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
    - run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
