name: Environment and Secrets

on:
  push:


jobs:
  dev-environment:
    name: Run on Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - run: echo "ENABLE_DEPLOYMENT=${{ vars.ENABLE_DEPLOYMENT }}"
    - run: echo "Running on ${{vars.ENV_NAME}} environment"

  prod-environment:
    name: Run on Prod
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main'
    needs: dev-environment
    steps:
    - run: echo "Running on ${{vars.ENV_NAME}} environment"

    - run: echo "DEPLOYING TO ${{ vars.ENV_NAME }}"
      if: ${{ vars.ENABLE_DEPLOYMENT == 'true' }}

    - run: echo "NOT DEPLOYING TO ${{ vars.ENV_NAME }} ${{ secrets.API_KEY }}"
      if: ${{ vars.ENABLE_DEPLOYMENT == 'false' }}

    - run: echo "API_KEY ${{ secrets.API_KEY }}"
